<Project>
  <PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.333" />
    <PackageVersion Include="System.Management" Version="10.0.12" />
    <PackageVersion Include="Tedd.WildcardMatch" Version="1.0.3" />
    <PackageVersion Include="Tedd.TUI" Version="1.3.13" />
    <PackageVersion Include="Tedd.TUI.Platform.Console" Version="1.3.13" />
    <PackageVersion Include="Tedd.TUI.Platform.WindowsTerminal" Version="1.3.13" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="11.0.0-preview.7.26406.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
