<Project>
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>0.1.0</Version>
    <Authors>Tedd</Authors>
    <Company>Tedd</Company>
    <Product>Tedd.Defrag</Product>
  </PropertyGroup>
</Project>
